name: Build iOS

on:
  push:
    branches:
      - main  # Change this if your branch is named "master" instead of "main"

jobs:
  build:
    runs-on: macos-latest  # GitHub Actions requires macOS for iOS builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"  # Use the latest Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign
